### ISSUE TITLE
Seperate server and client release

### ISSUE THREAD

**Issue by dorrywhale** [hellstein/ssh-rpc-agent-server#17]
Currently, the server and client are released in a single zip package, which is not the best choice.

**Comment by phigrey** [comment]
The project has been separated into [ssh-rpc-agent-server](https://github.com/hellstein/ssh-rpc-agent-server) and [ssh-rpc-agent-client](https://github.com/hellstein/ssh-rpc-agent-client), which will leads to UI version of the client side.
