### ISSUE TITLE
What is the Web UI used for?

### ISSUE THREAD

**Issue by able8** [hellstein/ssh-rpc-agent-server#20]
I do not quite understand why we need the web UI.
Is the web UI Only used to manipulate machines and tasks?

**Comment by able8** [comment]
You said that the Web UI would also prettify the output. Does it mean we will use the browser rather than the terminal to communicate with remote servers?

**Comment by dorrywhale** [comment]
Yes, that is right. So we can manage the machine, task on Web UI as well as the action

**Comment by dorrywhale** [comment]
And maybe starting another project is the best, leaving this one as a server
